version: "3.8"

services:

  db:
    container_name: db
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./numbers_api.sql:/docker-entrypoint-initdb.d/numbers_api.sql

  nums_api:
    container_name: nums_api
    image: nums_api
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DATABASE_URL_TEST=""
      - FLASK_APP=nums_api
    depends_on:
      - db

volumes:
  pgdata: {}


